name: 'Xcode Unit Testing'

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      # trigger on the main branch only for now
      - master
    paths:
      # only run tests when src code/configuration/this file has changed
      - '**.h'
      - '**.hpp'
      - '**.c'
      - '**.cpp'
      - '**.m'
      - '**.mm'
      - '**xcode-tests.yml'
      - 'RayTracing.xcodeproj/**'

jobs:
  build:
    strategy:
      matrix:
        os:
          # - macos-11
          - macos-latest
        # xcode:
        #   - ^12
        #   - ^13
        configuration:
          - Debug
            # - Release
        include:
          - configuration: Debug
            code-coverage: true
          # - configuration: Release
          #   code-coverage: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build & Test
        uses: mxcl/xcodebuild@v2.0.0
          with:
            action: test
            platform: macOS
            workspace: RayTracing.xcodeproj/project.xcworkspace
            scheme: RayTracing
            # xcode: ${{ matrix.xcode }}
            configuration: ${{ matrix.configuration }}
            code-sign-certificate: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
            code-sign-certificate-passphrase: ${{ secrets.BUILD_CERTIFICATE_PASSPHRASE }}
