on:
  push:
    branches:
      # trigger on the main branch only for now
      - master
    paths:
      # only run tests when src code/configuration/this file has changed
      - '**.h'
      - '**.hpp'
      - '**.c'
      - '**.cpp'
      - '**.m'
      - '**.mm'
      - '**xcode-tests.yml'
      - 'RayTracing.xcodeproj/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-11
        xcode:
          - ^12
          - ^13
        configuration:
          - Debug
            # - Release
        include:
          - configuration: Debug
            code-coverage: true
          # - configuration: Release
          #   code-coverage: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: mxcl/xcodebuild@v2.0.0
        with:
          xcode: ${{ matrix.xcode }}
          configuration: ${{ matrix.configuration }}
          platform: macOS
          action: test
          workspace: RayTracing.xcodeproj/project.xcworkspace
          scheme: RayTracing
